# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django_file_validator.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fooapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foomodel',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads/foomodel/img/', validators=[django_file_validator.validators.MaxSizeValidator(60)]),
        ),
    ]
