# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django_file_validator.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fooapp', '0002_auto_20160804_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foomodel',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads/foomodel/img/', validators=[django_file_validator.validators.MaxSizeValidator(1024)], verbose_name='Big Image'),
        ),
        migrations.AlterField(
            model_name='foomodel',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='foomodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/foomodel/img/', validators=[django_file_validator.validators.MaxSizeValidator()], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='foomodel',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads/foomodel/img/', validators=[django_file_validator.validators.MaxSizeValidator(60)], verbose_name='Small Image'),
        ),
    ]
